### ISSUE TITLE
object has no attribute 'request'

### ISSUE THREAD

**Issue by officiallymarky** [adafruit/Adafruit_CircuitPython_Requests#61]
I am trying to do a very basic import requests and query a url and I'm getting an error:

File  "adafruit_requests.py", line 692

AttributeError: 'NoneType' object has no attribute 'request'

My code is super simple.

```
import adafruit_requests as requests
response = requests.get('http://wifitest.adafruit.com/testwifi/index.html')
```

I am using this on a MagTag with the latest stable UF2 loader, and latest adafruit_request.mpy I can find.

**Comment by anecdata** [comment]
There needs to be code to include the kind of interface you are using, since there's no OS providing a connection and sockets. In this case, the native networking modules of the ESP32-S2 are needed. There are helper libraries for the MagTag, see:
[https://learn.adafruit.com/adafruit-magtag/circuitpython-libraries-2](https://learn.adafruit.com/adafruit-magtag/circuitpython-libraries-2)
Or, at a low level, use something more like:
```
import wifi
import socketpool
import ssl
import adafruit_requests
 
pool = socketpool.SocketPool(wifi.radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())
response = requests.get(URL)
```
Check out the Adafruit Learn Guides and examples for MagTag.

Closing.

**Comment by officiallymarky** [comment]
You can't use it with magtag.network.connect()?

**Comment by anecdata** [comment]
As I mentioned above, you can use the higher-level helper libraries, like MagTag and PortalBase. I'd suggest looking at some of the MagTag Learn Guides, or go on Discord to ask support questions.
