### ISSUE TITLE
OutOfRetries: Repeated socket failures

### ISSUE THREAD

**Issue by pjockey** [adafruit/Adafruit_CircuitPython_Requests#84]
Running a code for weather(https://learn.adafruit.com/weather-display-matrix) with the 64x32 LED board and and I keep getting the following error:
```
Retrieving data...Traceback (most recent call last):
  File "code.py", line 93, in <module>
  File "adafruit_portalbase/network.py", line 560, in fetch_data
  File "adafruit_portalbase/network.py", line 479, in fetch
  File "adafruit_requests.py", line 698, in get
  File "adafruit_requests.py", line 580, in request
OutOfRetries: Repeated socket failures

Code done running.

```
I'm running CP 7.0.0 with the libraries from 210928 and I had this same problem with CP 6.3.0.

Any ideas?

**Comment by pjockey** [comment]
These persist even with the newest Libraries.

**Comment by anecdata** [comment]
I do get these occasionally too, but catching and retrying usually works on the second time. You can also play with `timeout`. Generally, my escalation for network issues (because there are many potential causes, internal and external) is:

- retry (or retry with a longer timeout) ...several times; if it's not time-critical, wait some time before retrying
- disconnect / reconnect (ESP32SPI or ESP32-S2)
- if it's an ESP32SPI config, `esp.reset()`
- `supervisor.reload()`
- `microcontroller.reset()`

**Comment by askpatrickw** [comment]
I'm going to close this. It is the same issue that we're tracking and working on in #62
